parameters:
#    ove_thesaurus.example.class: OVE\ThesaurusBundle\Example

services:
#    ove_thesaurus.example:
#        class: %ove_thesaurus.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
