<?php

namespace OVE\ThesaurusBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * termeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class termeRepository extends EntityRepository
{
}
