<?php

namespace OVE\ThesaurusBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * thesaurusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class thesaurusRepository extends EntityRepository
{
}
